image: cenote/jasperstarter-env

pipelines:
  default:
    - step:
        script:
          - mvn clean package -P snapshot,windows-setup
          # upload new artifact to sourceforge downloads
          - ssh-keyscan -t rsa ${SF_HOST} >>  ~/.ssh/known_hosts
          - (umask 077; echo $SF_SSH_BASE64 | base64 --decode > ~/.ssh/id_rsa)
          - scp target/*.zip ${SF_USER}@${SF_HOST}:${SF_FILEBASE}/snapshots/

  tags:
    JasperStarter-*:
      - step:
          script:
            - mvn clean package -P release,windows-setup
            # upload release artifacts to sourceforge 
            - ssh-keyscan -t rsa ${SF_HOST} >>  ~/.ssh/known_hosts
            - (umask 077; echo $SF_SSH_BASE64 | base64 --decode > ~/.ssh/id_rsa)
            # creating the release directory name 
            - [[ "${BITBUCKET_TAG}" =~ .*-([0-9]+.[0-9]+) ]]
            - RELEASE_DIR=${BASH_REMATCH[0]}
            - echo $RELEASE_DIR
            - cd target && mkdir $RELEASE_DIR
            - scp -r $RELEASE_DIR ${SF_USER}@${SF_HOST}:${SF_FILEBASE}/snapshots/
            # uploading...
            - scp *.zip ${SF_USER}@${SF_HOST}:${SF_FILEBASE}/snapshots/$RELEASE_DIR


  branches:
    pipelinetest:
      - step:
          image: cenote/jasperstarter-env
          script:
            - mvn -version
            - mvn clean package -P snapshot
            # upload to bitbucket
            - ARTIFACT=$(ls -1 target/*.zip|head -n1)
            - ARTIFACT_BASENAME=$(basename $ARTIFACT)
            - curl -X POST -v --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"${ARTIFACT}"
            #- curl -X POST -v "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"${ARTIFACT}"
            # test from Bitbucket support
            - echo Hello World > hello2.txt
            - cat hello2.txt
            - echo "AUTH:" ${BB_AUTH_STRING}
            - echo "OWN:"  ${BITBUCKET_REPO_OWNER}
            - echo "SLUG:" ${BITBUCKET_REPO_SLUG}
            - curl -v -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@hello2.txt
